## Compute age-specific attributions for the four outcomes
library(tidyverse)
DM_FINETUNEDATA_DX_AGE.csv <- read.csv("~/GitHub/Doctoral-Research/BEHRT/DATA/FINETUNING_FEATURES/DM_FINETUNEDATA_DX_AGE.csv.gz")

CKD_ATTRIBUTIONS <- read.csv("D:/CKD_ATTRIBUTIONS.csv")
MACE_ATTRIBUTIONS <- read.csv("D:/MACE_ATTRIBUTIONS.csv")
RET_ATTRIBUTIONS <- read.csv("D:/RET_ATTRIBUTIONS.csv")
NEUR_ATTRIBUTIONS <- read.csv("D:/NEUR_ATTRIBUTIONS.csv")
### CKD
CKD_ID<-unique(CKD_ATTRIBUTIONS$PATIENT_ID)
FINETUNE_ID<-unique(DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID)

length(CKD_ID %in% FINETUNE_ID)
CKD_FINETUNE<-DM_FINETUNEDATA_DX_AGE.csv[DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID %in% CKD_ID, c(1:4,8:10)]
CKD_FINETUNE <- CKD_FINETUNE[order(CKD_FINETUNE$PATIENT_ID),]
CKD_ATTRIBUTIONS<-CKD_ATTRIBUTIONS[,2:8]

## Convert columns to dates
CKD_ATTRIBUTIONS$ADMIT_DATE <- as.Date(CKD_ATTRIBUTIONS$ADMIT_DATE)
CKD_ATTRIBUTIONS$DISCHARGE_DATE <- as.Date(CKD_ATTRIBUTIONS$DISCHARGE_DATE)

CKD_FINETUNE$ADMIT_DATE<-as.Date(CKD_FINETUNE$ADMIT_DATE)
CKD_FINETUNE$DISCHARGE_DATE <- as.Date(CKD_FINETUNE$DISCHARGE_DATE)

CKD_FINETUNE_AGE<-CKD_FINETUNE %>%
  distinct(PATIENT_ID, ADMIT_DATE, DISCHARGE_DATE,AGE_AT_ENC,.keep_all = TRUE)


CKD_ATTR_AGE_SEX<-CKD_ATTRIBUTIONS %>%
  left_join(CKD_FINETUNE_AGE ,by=c("PATIENT_ID", "ADMIT_DATE", "DISCHARGE_DATE"), relationship = "many-to-many")


### MACE
MACE_ID<-unique(MACE_ATTRIBUTIONS$PATIENT_ID)
FINETUNE_ID<-unique(DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID)

length(MACE_ID %in% FINETUNE_ID)
MACE_FINETUNE<-DM_FINETUNEDATA_DX_AGE.csv[DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID %in% MACE_ID, c(1:4,8:10)]
MACE_FINETUNE <- MACE_FINETUNE[order(MACE_FINETUNE$PATIENT_ID),]
MACE_ATTRIBUTIONS<-MACE_ATTRIBUTIONS[,2:8]

## Convert columns to dates
MACE_ATTRIBUTIONS$ADMIT_DATE <- as.Date(MACE_ATTRIBUTIONS$ADMIT_DATE)
MACE_ATTRIBUTIONS$DISCHARGE_DATE <- as.Date(MACE_ATTRIBUTIONS$DISCHARGE_DATE)

MACE_FINETUNE$ADMIT_DATE<-as.Date(MACE_FINETUNE$ADMIT_DATE)
MACE_FINETUNE$DISCHARGE_DATE <- as.Date(MACE_FINETUNE$DISCHARGE_DATE)

MACE_FINETUNE_AGE<-MACE_FINETUNE %>%
  distinct(PATIENT_ID, ADMIT_DATE, DISCHARGE_DATE,AGE_AT_ENC,.keep_all = TRUE)


MACE_ATTR_AGE_SEX<-MACE_ATTRIBUTIONS %>%
  left_join(MACE_FINETUNE_AGE ,by=c("PATIENT_ID", "ADMIT_DATE", "DISCHARGE_DATE"), relationship = "many-to-many")

### RET

RET_ID<-unique(RET_ATTRIBUTIONS$PATIENT_ID)
FINETUNE_ID<-unique(DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID)

length(RET_ID %in% FINETUNE_ID)
RET_FINETUNE<-DM_FINETUNEDATA_DX_AGE.csv[DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID %in% RET_ID, c(1:4,8:10)]
RET_FINETUNE <- RET_FINETUNE[order(RET_FINETUNE$PATIENT_ID),]
RET_ATTRIBUTIONS<-RET_ATTRIBUTIONS[,2:8]

## Convert columns to dates
RET_ATTRIBUTIONS$ADMIT_DATE <- as.Date(RET_ATTRIBUTIONS$ADMIT_DATE)
RET_ATTRIBUTIONS$DISCHARGE_DATE <- as.Date(RET_ATTRIBUTIONS$DISCHARGE_DATE)

RET_FINETUNE$ADMIT_DATE<-as.Date(RET_FINETUNE$ADMIT_DATE)
RET_FINETUNE$DISCHARGE_DATE <- as.Date(RET_FINETUNE$DISCHARGE_DATE)

RET_FINETUNE_AGE<-RET_FINETUNE %>%
  distinct(PATIENT_ID, ADMIT_DATE, DISCHARGE_DATE,AGE_AT_ENC,.keep_all = TRUE)


RET_ATTR_AGE_SEX<-RET_ATTRIBUTIONS %>%
  left_join(RET_FINETUNE_AGE ,by=c("PATIENT_ID", "ADMIT_DATE", "DISCHARGE_DATE"), relationship = "many-to-many")

##NEUR
NEUR_ID<-unique(NEUR_ATTRIBUTIONS$PATIENT_ID)
FINETUNE_ID<-unique(DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID)

length(NEUR_ID %in% FINETUNE_ID)
NEUR_FINETUNE<-DM_FINETUNEDATA_DX_AGE.csv[DM_FINETUNEDATA_DX_AGE.csv$PATIENT_ID %in% NEUR_ID, c(1:4,8:10)]
NEUR_FINETUNE <- NEUR_FINETUNE[order(NEUR_FINETUNE$PATIENT_ID),]
NEUR_ATTRIBUTIONS<-NEUR_ATTRIBUTIONS[,2:8]

## Convert columns to dates
NEUR_ATTRIBUTIONS$ADMIT_DATE <- as.Date(NEUR_ATTRIBUTIONS$ADMIT_DATE)
NEUR_ATTRIBUTIONS$DISCHARGE_DATE <- as.Date(NEUR_ATTRIBUTIONS$DISCHARGE_DATE)

NEUR_FINETUNE$ADMIT_DATE<-as.Date(NEUR_FINETUNE$ADMIT_DATE)
NEUR_FINETUNE$DISCHARGE_DATE <- as.Date(NEUR_FINETUNE$DISCHARGE_DATE)

NEUR_FINETUNE_AGE<-NEUR_FINETUNE %>%
  distinct(PATIENT_ID, ADMIT_DATE, DISCHARGE_DATE,AGE_AT_ENC,.keep_all = TRUE)

NEUR_ATTR_AGE_SEX<-NEUR_ATTRIBUTIONS %>%
  left_join(NEUR_FINETUNE_AGE ,by=c("PATIENT_ID", "ADMIT_DATE", "DISCHARGE_DATE"), relationship = "many-to-many")


### Saving csv
### 
write.csv(CKD_ATTR_AGE_SEX, "D:/CKD_ATTR_AGE_SEX.csv")
write.csv(MACE_ATTR_AGE_SEX, "D:/MACE_ATTR_AGE_SEX.csv")
write.csv(RET_ATTR_AGE_SEX, "D:/RET_ATTR_AGE_SEX.csv")
write.csv(NEUR_ATTR_AGE_SEX, "D:/NEUR_ATTR_AGE_SEX.csv")

