apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretrain-dx
spec:
  storageClassName: rook-cephfs-central	
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi